### ISSUE TITLE
Add VST support to Linux

### ISSUE THREAD

**Issue by ngeiswei** [reduz/zytrax#4]
VST is currently not supported for Linux.

If I enable it for Linux in SConstruct I get the following error
```bash
drivers/vst2/audio_effect_vst2.h:9:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
```

I don't understand why it requires `windows.h`, I suppose in principle it shouldn't require it.

If I merely comment out that include, then I get the following error
```bash
In file included from drivers/vst2/audio_effect_vst2.h:6,
                 from drivers/vst2/audio_effect_vst2.cpp:1:
drivers/vst2/vestige.h:231:28: error: expected identifier before ‘*’ token
  intptr_t VESTIGECALLBACK (*dispatcher)(AEffect *, int, int, intptr_t, void *, float);
```

Not sure what to do from there. I'm investigating, but I welcome help as well.

**Comment by ngeiswei** [comment]
If I replace `vestige.h` by https://github.com/ngeiswei/ardour/blob/master/libs/ardour/ardour/vestige/vestige.h I'm getting an error about `HINSTANCE` which seems to be a Win32 type.
```bash
In file included from drivers/vst2/audio_effect_vst2.cpp:1:
drivers/vst2/audio_effect_vst2.h:34:2: error: ‘HINSTANCE’ does not name a type
  HINSTANCE libhandle;
  ^~~~~~~~~
```

**Comment by reduz** [comment]
As far as I understand it's not the same on Linux because the plugin UI has to run on a separate thread, so all the embedding code is different and needs to be re-written. I don't currently have the time to do that, but I think Ardour (which also uses Gtkmm) could be used as reference. Also I suppose the plugin loading must likely needs to be modified to use dlopen().

**Comment by reduz** [comment]
Well, ended up doing it.. closing.

**Comment by ngeiswei** [comment]
Thank you so much! BTW, with Carla one can actually load LV2 as well (with the drawback that accessing parameters is more convoluted).
