### ISSUE TITLE
This would be really cool if it would be based on buzz tracker style

### ISSUE THREAD

**Issue by michaelsjackson** [reduz/zytrax#6]
Meaning having the fantastic sequence editor of buzz! There is already buze for wine, but having just another buzz style alternative is never bad. Did not try your tool yet. There is also hackey trackey lua plugin for Reaper DAW. There you have then also great tracker workflow using all advantages of vsti and DAWs, best of both worlds, thanks to saike! Maybe worth a look at that and improving that instead? Just a side input thought. Btw. thanks for godot! Just discovered it recently indirectly via Blender. Will explore it more in future.

buzz tracker, Reaper DAW, sequetron by Phil Tipping:  music side of things
blender, godot 3: gaming side of things

Now I am trying to figure out, how to create a game, at the push of a button, using some prepared resources on harddisk, like 100 .png images, 100 .svg files, 100 lines of text in a .txt file. Goal would be designing various games in such a way, they would just auto-import those resources and the game would immediately start. You want a different variant, just replace those resources, re-generate, it would be a similar game, but not exactly same. One could imagine each such game like a scene maybe? Any tools which can do this already?

**Comment by reduz** [comment]
Sorry, not intending to do something like Buzz.
